#!/bin/sh

if [ "$(pactl list short sinks | cut -f2 | cut -d. -f4)" = "analog-stereo" ]; then
	pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo
else
	pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi

pkill -RTMIN+1 i3blocks
